--------------------------------------------------------
--  File created - Wednesday-May-13-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T24RESPONSE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."T24RESPONSE" 
   (	"MTIREQ" VARCHAR2(20 BYTE), 
	"MTIRES" VARCHAR2(20 BYTE), 
	"PCODE" VARCHAR2(20 BYTE), 
	"RESPONSE" BLOB, 
	"REQUEST" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("RESPONSE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("REQUEST") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into SYSTEM.T24RESPONSE
SET DEFINE OFF;
Insert into SYSTEM.T24RESPONSE (MTIREQ,MTIRES,PCODE) values ('0200','0210','31');
Insert into SYSTEM.T24RESPONSE (MTIREQ,MTIRES,PCODE) values ('0200','0210','40');
Insert into SYSTEM.T24RESPONSE (MTIREQ,MTIRES,PCODE) values ('0800','0810','80');
Insert into SYSTEM.T24RESPONSE (MTIREQ,MTIRES,PCODE) values ('0200','0210','54');
