CREATE TABLE "SYSTEM"."ERROR_AUDIT_LOGGING" 
   (	"MSGID" VARCHAR2(100 BYTE), 
	"LOGGING_TIME" TIMESTAMP (6), 
	"MESSAGE" CLOB, 
	"MESSAGETYPE" VARCHAR2(100 BYTE), 
	"APPNAME" VARCHAR2(100 BYTE), 
	"BROKER" VARCHAR2(100 BYTE), 
	"ERRORDESCRIPTION" CLOB
   ) 
   
   
   
   CREATE TABLE "SYSTEM"."RAW_AUDIT_LOGGING" 
   (	"MSGID" VARCHAR2(100 BYTE), 
	"LOGGING_TIME" TIMESTAMP (6), 
	"MESSAGE" CLOB, 
	"MESSAGETYPE" VARCHAR2(100 BYTE), 
	"APPNAME" VARCHAR2(100 BYTE), 
	"BROKER" VARCHAR2(100 BYTE)
   )
   
   
create or replace PROCEDURE INSERT_ERROR_AUDIT_LOGGING 
(
  MSG_ID IN VARCHAR2 
, LOGGINGTIME IN TIMESTAMP 
,MESSAGE_DATA IN VARCHAR2
, MESSAGE_TYPE IN VARCHAR2 
, APP_NAME IN VARCHAR2 
, BROKER_NAME IN VARCHAR2 
,ERROR_DESCRIPTION IN VARCHAR2
) AS 
BEGIN
 INSERT INTO ERROR_AUDIT_LOGGING(MSGID,LOGGING_TIME,MESSAGE,MESSAGETYPE,APPNAME,BROKER,ERRORDESCRIPTION) VALUES(MSG_ID,LOGGINGTIME,MESSAGE_DATA,MESSAGE_TYPE,APP_NAME,BROKER_NAME,ERROR_DESCRIPTION);
END INSERT_ERROR_AUDIT_LOGGING; 




create or replace PROCEDURE INSERT_RAW_AUDIT 
(
  MSG_ID IN VARCHAR2 
, LOGGINGTIME IN TIMESTAMP 
,MESSAGE_DATA IN VARCHAR2
, MESSAGE_TYPE IN VARCHAR2 
, APP_NAME IN VARCHAR2 
, BROKER_NAME IN VARCHAR2 
) AS 
BEGIN
 INSERT INTO RAW_AUDIT_LOGGING(MSGID,LOGGING_TIME,MESSAGE,MESSAGETYPE,APPNAME,BROKER) VALUES(MSG_ID,LOGGINGTIME,MESSAGE_DATA,MESSAGE_TYPE,APP_NAME,BROKER_NAME);
END INSERT_RAW_AUDIT;
