--------------------------------------------------------
--  File created - Sunday-April-26-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HTTP_FLOW_DETAILS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."HTTP_FLOW_DETAILS" 
   (	"HTTP_REQUEST_IDENTIFIER" BLOB, 
	"CUR_TIMESTAMP" TIMESTAMP (6), 
	"TRANSACTION_STATUS" VARCHAR2(20 BYTE), 
	"TRANSACTION_DESC" VARCHAR2(1000 BYTE), 
	"ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("HTTP_REQUEST_IDENTIFIER") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index HTTP_FLOW_DETAILS_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."HTTP_FLOW_DETAILS_INDEX1" ON "SYSTEM"."HTTP_FLOW_DETAILS" ("CUR_TIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table HTTP_FLOW_DETAILS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."HTTP_FLOW_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
