create PROCEDURE INSERT_ERROR_AUDIT_LOGGING
(
@MSG_ID VARCHAR(4000)
, @LOGGINGTIME DATETIME2(6)
,@MESSAGE_DATA VARCHAR(4000)
, @MESSAGE_TYPE VARCHAR(4000)
, @APP_NAME VARCHAR(4000)
, @BROKER_NAME VARCHAR(4000)
,@ERROR_DESCRIPTION VARCHAR(4000)
,@TIME_LOCAL_TRANSACTION VARCHAR(4000)
,@DATE_LOCAL_TRANSACTION VARCHAR(4000)
,@RETRIEVAL_REFERENCE_NUMBER VARCHAR(4000)
,@BORKER_ERROR_CODE VARCHAR(200)
,@USER_DEFINE_ERROR_CODE VARCHAR(4000)
) AS
BEGIN
SET NOCOUNT ON;
INSERT INTO ERROR_AUDIT_LOGGING(MSGID,LOGGING_TIME,MESSAGE,MESSAGETYPE,APPNAME,BROKER,ERRORDESCRIPTION,TIME_LOCAL_TRANSACTION,DATE_LOCAL_TRANSACTION,RETRIEVAL_REFERENCE_NUMBER,BORKER_ERROR_CODE,USER_DEFINE_ERROR_CODE) VALUES(@MSG_ID,@LOGGINGTIME,@MESSAGE_DATA,@MESSAGE_TYPE,@APP_NAME,@BROKER_NAME,@ERROR_DESCRIPTION,@TIME_LOCAL_TRANSACTION,@DATE_LOCAL_TRANSACTION,@RETRIEVAL_REFERENCE_NUMBER,@BORKER_ERROR_CODE,@USER_DEFINE_ERROR_CODE);
END;