--------------------------------------------------------
--  File created - Monday-July-06-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table INTEGRATION_SOL_DETAILS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."INTEGRATION_SOL_DETAILS" 
   (	"PROC_CODE" VARCHAR2(20 BYTE), 
	"REQ_QUEUE" VARCHAR2(20 BYTE), 
	"RES_QUEUE" VARCHAR2(20 BYTE), 
	"HTTP_REQ" VARCHAR2(20 BYTE), 
	"HTTP_RES" VARCHAR2(20 BYTE), 
	"CHANNEL" VARCHAR2(20 BYTE), 
	"MSGDOMAIN" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.INTEGRATION_SOL_DETAILS
SET DEFINE OFF;
Insert into SYSTEM.INTEGRATION_SOL_DETAILS (PROC_CODE,REQ_QUEUE,RES_QUEUE,HTTP_REQ,HTTP_RES,CHANNEL,MSGDOMAIN) values ('63',null,null,'KANZ_SB_HTTP_REQ','ALL_SB_HTTP_RES','MobileApp','JSON');
Insert into SYSTEM.INTEGRATION_SOL_DETAILS (PROC_CODE,REQ_QUEUE,RES_QUEUE,HTTP_REQ,HTTP_RES,CHANNEL,MSGDOMAIN) values ('33','CURCON_SB_TCP_REQ','ALL_SB_TCP_RES','CURCON_SB_HTTP_REQ','ALL_SB_HTTP_RES','MobileWorld','JSON');
Insert into SYSTEM.INTEGRATION_SOL_DETAILS (PROC_CODE,REQ_QUEUE,RES_QUEUE,HTTP_REQ,HTTP_RES,CHANNEL,MSGDOMAIN) values ('42',null,null,'ZIPIT_SB_HTTP_REQ','ALL_SB_HTTP_RES','MobileApp','JSON');
Insert into SYSTEM.INTEGRATION_SOL_DETAILS (PROC_CODE,REQ_QUEUE,RES_QUEUE,HTTP_REQ,HTTP_RES,CHANNEL,MSGDOMAIN) values ('54',null,null,'RTGS_SB_HTTP_REQ','ALL_SB_HTTP_RES','MobileApp','JSON');
Insert into SYSTEM.INTEGRATION_SOL_DETAILS (PROC_CODE,REQ_QUEUE,RES_QUEUE,HTTP_REQ,HTTP_RES,CHANNEL,MSGDOMAIN) values ('42','ZIPIT_SEN_SB_TCP_REQ','ALL_SB_TCP_RES',null,null,null,'ISO');
Insert into SYSTEM.INTEGRATION_SOL_DETAILS (PROC_CODE,REQ_QUEUE,RES_QUEUE,HTTP_REQ,HTTP_RES,CHANNEL,MSGDOMAIN) values ('31','BE_SB_TCP_REQ','ALL_SB_TCP_RES',null,null,null,'ISO');
Insert into SYSTEM.INTEGRATION_SOL_DETAILS (PROC_CODE,REQ_QUEUE,RES_QUEUE,HTTP_REQ,HTTP_RES,CHANNEL,MSGDOMAIN) values ('31',null,null,'BE_SB_HTTP_REQ','ALL_SB_HTTP_RES','MobileApp','JSON');
Insert into SYSTEM.INTEGRATION_SOL_DETAILS (PROC_CODE,REQ_QUEUE,RES_QUEUE,HTTP_REQ,HTTP_RES,CHANNEL,MSGDOMAIN) values ('01','WD_SB_TCP_REQ','ALL_SB_TCP_RES',null,null,null,'ISO');
Insert into SYSTEM.INTEGRATION_SOL_DETAILS (PROC_CODE,REQ_QUEUE,RES_QUEUE,HTTP_REQ,HTTP_RES,CHANNEL,MSGDOMAIN) values ('21','DP_SB_TCP_REQ','ALL_SB_TCP_RES',null,null,null,'ISO');
Insert into SYSTEM.INTEGRATION_SOL_DETAILS (PROC_CODE,REQ_QUEUE,RES_QUEUE,HTTP_REQ,HTTP_RES,CHANNEL,MSGDOMAIN) values ('29',null,null,'ACCOPN_SB_HTTP_REQ','ALL_SB_HTTP_RES','Sosholoza','JSON');
